### ISSUE TITLE
Buttons are tiny on 4k

### ISSUE THREAD

**Issue by Gingernaut** [MarianArlt/breeze-osx-decorations#1]
I really like the theme! However on a 4k screen buttons are extremely tiny. 

Side question, how do you move the buttons from the right to the left?

Thanks for the theme!

**Comment by Gingernaut** [comment]
I was able to figure out what I needed. Thanks anyways!

**Comment by MarianArlt** [comment]
Been on vacations a few weeks. Glad you could find it out yourself!

**Comment by Gingernaut** [comment]
I figured out the scaling but I couldn't figure out the left/right buttons. What value should I change the" LeftButtons=XIA" value to have it mimic MacOS?

**Comment by MarianArlt** [comment]
That's a natural Plasma feature. Go to settings > Window decorations
If you pay close attention you'll notice there are two tabs. Theme & Buttons
In the Buttons tab you can drag & drop the buttons of the Title bar to the left or right or even remove them and add others. Not every theme has buttons specifically designed for all window functions though.
